package sherry.datapoint.domain;

public class DataPointDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datapoint.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datapoint.device_id
     *
     * @mbg.generated
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datapoint.water_in_t
     *
     * @mbg.generated
     */
    private Float waterInT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datapoint.water_out_t
     *
     * @mbg.generated
     */
    private Float waterOutT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datapoint.id
     *
     * @return the value of datapoint.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datapoint.id
     *
     * @param id the value for datapoint.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datapoint.device_id
     *
     * @return the value of datapoint.device_id
     *
     * @mbg.generated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datapoint.device_id
     *
     * @param deviceId the value for datapoint.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datapoint.water_in_t
     *
     * @return the value of datapoint.water_in_t
     *
     * @mbg.generated
     */
    public Float getWaterInT() {
        return waterInT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datapoint.water_in_t
     *
     * @param waterInT the value for datapoint.water_in_t
     *
     * @mbg.generated
     */
    public void setWaterInT(Float waterInT) {
        this.waterInT = waterInT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datapoint.water_out_t
     *
     * @return the value of datapoint.water_out_t
     *
     * @mbg.generated
     */
    public Float getWaterOutT() {
        return waterOutT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datapoint.water_out_t
     *
     * @param waterOutT the value for datapoint.water_out_t
     *
     * @mbg.generated
     */
    public void setWaterOutT(Float waterOutT) {
        this.waterOutT = waterOutT;
    }
}