package sherry.datapoint.mapper;

import sherry.datapoint.domain.DataPointDao;

public interface DataPointDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datapoint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datapoint
     *
     * @mbg.generated
     */
    int insert(DataPointDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datapoint
     *
     * @mbg.generated
     */
    int insertSelective(DataPointDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datapoint
     *
     * @mbg.generated
     */
    DataPointDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datapoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataPointDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datapoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataPointDao record);
}